var constants = {
	COL_SIZE: 101,
	ROW_SIZE: 83,

	DEFAULT_NUM_COLS: 5,
	DEFAULT_NUM_ROWS: 6,

	PLAYER_MARGIN: 30,

	MIN_NUM_COLS: 1,
	MIN_NUM_ROWS: 4,
	DEFAULT_PLAYER_IMAGE: "images/char-boy.png",
	DEFAULT_NUM_ENEMIES: 2
};
